#!/usr/bin/env python3
"""Encode the "unsettled terms" appendix.

Some English terms have no settled Vietnamese translation: they are either
untranslatable, translated only by ad-hoc calques, or have several competing
renderings with no clear winner. Such terms do not fit the main A-Z lexicon
(which records exactly one recommended Vietnamese term per entry), so they live
in a separate appendix that lists the candidate renderings WITHOUT picking one.

Source of truth: workflow/panels/appendix-unsettled-final.json
Outputs:
  - source/appendix-unsettled.ptx        (a PreTeXt <appendix>, included in backmatter)
  - data/terms/appendix-unsettled.yaml   (data record; intentionally NOT named
                                          entries-*.yaml so validate-entry.py
                                          skips the one-recommended rule)

Each panel entry: id, headword_en, pos, notation, definition_vi, example_vi,
ref_bib, rosen_ref, candidates [{term, source_id?, page?}], notes.
"""
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Reuse the chapter encoder's prose/math helpers (filename is hyphenated, so
# load it by path rather than a plain import).
import importlib.util  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "encode_chapter", os.path.join(os.path.dirname(os.path.abspath(__file__)), "encode-chapter.py"))
_ec = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_ec)
esc_text, to_ptx = _ec.esc_text, _ec.to_ptx


def render_entry(e):
    eid = e["id"]
    pos = f" ({e['pos']})" if e.get("pos") else ""
    title = esc_text(e["headword_en"]) + pos
    lines = [f'  <definition xml:id="apx-{eid}">',
             f"    <title>{title}</title>",
             f"    <idx><h>{esc_text(e['headword_en'])}</h></idx>"]
    for c in e.get("candidates", []):
        term = (c.get("term", "") or "").replace("$$", "").strip()
        if term:
            lines.append(f"    <idx><h>{esc_text(term)}</h></idx>")
    lines.append("    <statement>")
    raw = (e.get("definition_vi", "") or "").rstrip()
    has_src = e.get("rosen_ref") or e.get("ref_bib")
    if has_src and raw.endswith("."):
        raw = raw[:-1].rstrip()
    defn = to_ptx(raw)
    if has_src:
        ref_bib = e.get("ref_bib", "bib-rosen-2019")
        loc = (", " + esc_text(e["rosen_ref"])) if e.get("rosen_ref") else ""
        defn += f' (theo <xref ref="{ref_bib}" />{loc}).'
    lines.append(f"      <p>{defn}</p>")
    lines.append("      <p>Chưa có cách dịch tiếng Việt thống nhất. Một số phương án "
                 "đã được dùng hoặc đề xuất:</p>")
    lines.append("      <ul>")
    for c in e.get("candidates", []):
        term = (c.get("term", "") or "").strip()
        if not term:
            continue
        body = f"<term>{esc_text(term)}</term>"
        sid, page = c.get("source_id", ""), str(c.get("page", "")).strip()
        if sid:
            body += f' <xref ref="{sid}" />' + (f" ({esc_text(page)})" if page else "")
        else:
            body += " <em>(chưa có trích dẫn cụ thể)</em>"
        lines.append(f"        <li><p>{body}.</p></li>")
    lines.append("      </ul>")
    if e.get("notes"):
        lines.append(f"      <p>{to_ptx(e['notes'])}</p>")
    if e.get("example_vi"):
        lines.append(f"      <p>Ví dụ: {to_ptx(e['example_vi'])}</p>")
    lines.append("    </statement>")
    lines.append("  </definition>")
    return "\n".join(lines)


def main():
    src = os.path.join(ROOT, "workflow", "panels", "appendix-unsettled-final.json")
    data = json.load(open(src, encoding="utf-8"))
    entries = sorted(data["entries"], key=lambda e: e["headword_en"].lower())

    # ---- data/terms/appendix-unsettled.yaml ----
    ydoc = {"appendix": "unsettled", "entries": entries}
    ypath = os.path.join(ROOT, "data", "terms", "appendix-unsettled.yaml")
    with open(ypath, "w", encoding="utf-8") as fh:
        fh.write("# Unsettled-terms appendix. Source of truth.\n")
        fh.write("# Generated by encode-appendix.py from "
                 "workflow/panels/appendix-unsettled-final.json\n")
        yaml.safe_dump(ydoc, fh, allow_unicode=True, sort_keys=False, width=100)

    # ---- source/appendix-unsettled.ptx ----
    body = [render_entry(e) for e in entries]
    ptx = f'''<?xml version="1.0" encoding="UTF-8"?>
<appendix xml:id="appendix-unsettled" xmlns:xi="http://www.w3.org/2001/XInclude">
  <title>Các thuật ngữ chưa có cách dịch thống nhất</title>

  <introduction>
    <p>
      Phụ lục này tập hợp các thuật ngữ tiếng Anh mà tại thời điểm biên soạn
      chưa có cách dịch tiếng Việt thống nhất: hoặc chưa có cách dịch quen thuộc,
      hoặc tồn tại nhiều cách dịch khác nhau mà chưa rõ cách nào là chính xác
      nhất. Khác với các mục trong phần chính, các mục ở đây <em>không</em> đề
      xuất một thuật ngữ tiếng Việt ưu tiên; thay vào đó, chúng tôi liệt kê các
      phương án đã gặp để bạn đọc tham khảo và cân nhắc.
    </p>
  </introduction>

{chr(10).join(body)}
</appendix>
'''
    ppath = os.path.join(ROOT, "source", "appendix-unsettled.ptx")
    open(ppath, "w", encoding="utf-8").write(ptx)
    print(f"Wrote {len(entries)} appendix entries -> "
          f"{os.path.relpath(ypath, ROOT)} and {os.path.relpath(ppath, ROOT)}")


if __name__ == "__main__":
    main()
