#!/usr/bin/env python3
"""Generate the acknowledgements preface (source/acknowledgements.ptx).

The thanks list merges two sources into ONE uniformly formatted, alphabetically
sorted list:
  1. data/contributors-email.txt        - people who sent feedback by email.
       One per line; '#' starts a comment. Optional affiliation after a '|':
           Trần Thị Bình | Trường Đại học Khoa học Tự nhiên
       Shown with a person icon, full name, and affiliation (if given).
  2. workflow/acknowledgements/merged-prs.json - authors of accepted (merged)
       pull requests, as produced by
       `gh pr list --state merged --json number,title,author,mergedAt`.
       Shown with a GitHub icon and the author's GitHub username.

Channel icons are emitted as portable tokens (@@person@@ / @@github@@) that the
PDF patcher (patch-cover-tex.py) and the web post-processor (postprocess-web.py)
rewrite to FontAwesome glyphs. The PR file is optional, so a local build with no
GitHub data still works.
"""
from __future__ import annotations

import json
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EMAIL_TXT = ROOT / "data" / "contributors-email.txt"
PR_JSON = ROOT / "workflow" / "acknowledgements" / "merged-prs.json"
OUT = ROOT / "source" / "acknowledgements.ptx"

# Logins never credited as external contributors: the editor and bots.
EXCLUDE_LOGINS = {"hoanganhduc"}
EDITOR = "Duc A. Hoang (Hoàng Anh Đức)"

PERSON_ICON = "@@person@@"
GITHUB_ICON = "@@github@@"


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def sort_key(name: str) -> str:
    """Case- and diacritics-folded key for a stable alphabetical order."""
    folded = unicodedata.normalize("NFKD", name)
    folded = "".join(c for c in folded if not unicodedata.combining(c))
    return folded.casefold().lstrip("@")


def read_email_contributors() -> list[tuple[str, str]]:
    """(full name, affiliation) pairs; affiliation is '' when absent."""
    if not EMAIL_TXT.exists():
        return []
    people: list[tuple[str, str]] = []
    for line in EMAIL_TXT.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, _, affil = line.partition("|")
        people.append((name.strip(), affil.strip()))
    return people


def read_pr_usernames() -> list[str]:
    """Distinct GitHub usernames of merged-PR authors (editor/bots excluded)."""
    if not PR_JSON.exists():
        return []
    try:
        prs = json.loads(PR_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    seen: dict[str, str] = {}
    for pr in prs or []:
        author = pr.get("author") or {}
        login = (author.get("login") or "").strip()
        if not login or login.lower() in EXCLUDE_LOGINS or login.endswith("[bot]"):
            continue
        seen.setdefault(login.lower(), login)
    return list(seen.values())


def build_entries() -> list[str]:
    """Rendered <li> bodies, one per contributor, merged and alphabetized.

    Email contributors: person icon + full name + (affiliation). PR
    contributors: GitHub icon + username. Sorted by the displayed name."""
    rows: list[tuple[str, str]] = []  # (sort name, rendered body)
    for name, affil in read_email_contributors():
        body = f"{PERSON_ICON} {esc(name)}"
        if affil:
            body += f" ({esc(affil)})"
        rows.append((name, body))
    for login in read_pr_usernames():
        rows.append((login, f"{GITHUB_ICON} {esc(login)}"))
    rows.sort(key=lambda r: sort_key(r[0]))
    return [body for _, body in rows]


def render(bodies: list[str]) -> str:
    intro = (
        f"      Cùng với người biên soạn, <term>{esc(EDITOR)}</term>, nhiều người đã\n"
        "      góp phần làm cuốn sách tốt hơn — qua góp ý gửi tới hòm thư biên tập hoặc\n"
        "      qua các pull request đã được tích hợp trên kho mã nguồn GitHub."
    )
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- GENERATED by workflow/scripts/gen-acknowledgements.py — do not edit by hand. -->",
        '<preface xml:id="acknowledgements" xmlns:xi="http://www.w3.org/2001/XInclude">',
        "  <title>Lời cảm ơn</title>",
        "",
        f"  <p>\n{intro}\n  </p>",
    ]
    if bodies:
        parts.append("")
        parts.append("  <p>Xin chân thành cảm ơn những đóng góp sau (xếp theo thứ tự bảng chữ cái):</p>")
        parts.append("  <ul>")
        parts.extend(f"    <li><p>{body}</p></li>" for body in bodies)
        parts.append("  </ul>")
    else:
        parts.append("")
        parts.append("  <p>Danh sách đóng góp sẽ được cập nhật khi có góp ý đầu tiên.</p>")
    parts.append("")
    parts.append(
        "  <p>\n"
        "      Danh sách trên được cập nhật tự động mỗi khi xây dựng cuốn sách. Nếu bạn\n"
        "      đã đóng góp nhưng chưa thấy tên mình, xin liên hệ\n"
        "      <email>hoanganhduc@hus.edu.vn</email>.\n"
        "  </p>"
    )
    parts.append("</preface>")
    return "\n".join(parts) + "\n"


def main() -> None:
    bodies = build_entries()
    OUT.write_text(render(bodies), encoding="utf-8")
    print(f"Wrote {len(bodies)} contributor(s) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
